dist: xenial
git: 
  depth: 25
  quiet: true
group: travis_latest
matrix: 
  include: 
    - 
      language: python
      python: 3.7
      script: 
        - "flake8 --extend-ignore=W,E1,E2,E3,E5"
    - 
      language: node_js
      node_js: 
        - node
      script: 
        - "npm run test"
